In [2]:
import pickle
import numpy as np
import pandas as pd
from copy import deepcopy

In [171]:
base_model = 'lr'
data = 'correction'

df_results = pd.read_pickle(f'../results/comparison_{base_model}_{data}.pkl')

In [172]:
df_results.sort_values('alg')

,alg,seed,alpha,lambda,Cost,M1 Validity,WC Validity,M1 Expectation,WC Expectation,J,Loss
0,OPT,0,0.5,0.2,4.626025,1.000000,0.875000,0.716056,0.528740,1.564183,0.638978
2,OPT,1,0.5,0.2,5.568962,1.000000,0.833333,0.709723,0.546689,1.722250,0.608458
4,OPT,2,0.5,0.2,5.714758,1.000000,0.454545,0.713369,0.482079,1.903395,0.760443
6,OPT,3,0.5,0.2,4.525096,1.000000,0.533333,0.705098,0.507814,1.589541,0.684522
8,OPT,4,0.5,0.2,5.685610,1.000000,0.857143,0.736234,0.543768,1.755108,0.617986
1,ROAR,0,0.5,0.2,2.594445,0.687500,0.062500,0.583903,0.268573,2.332159,1.813270
3,ROAR,1,0.5,0.2,2.557872,0.666667,0.000000,0.538501,0.228037,2.825758,2.314184
5,ROAR,2,0.5,0.2,3.928376,0.909091,0.000000,0.617516,0.333619,2.287244,1.501569
7,ROAR,3,0.5,0.2,3.666644,1.000000,0.066667,0.652781,0.392463,1.700974,0.967645
9,ROAR,4,0.5,0.2,4.827631,0.928571,0.071429,0.659122,0.367373,2.054141,1.088615

In [152]:
df_results_avg = df_results.groupby('alg').mean()
df_results_avg[['Cost', 'M1 Validity', 'WC Validity', 'M1 Expectation', 'WC Expectation',  'J', 'Loss']] = df_results_avg[['Cost', 'M1 Validity', 'WC Validity', 'M1 Expectation', 'WC Expectation', 'J', 'Loss']].round(2).astype(str) + '±' + df_results.groupby('alg').std()[['Cost', 'M1 Validity', 'WC Validity', 'M1 Expectation', 'WC Expectation', 'J', 'Loss']].round(2).astype(str)

print(f'{data}, {base_model}')
df_results_avg

correction, lr

,seed,alpha,lambda,Cost,M1 Validity,WC Validity,M1 Expectation,WC Expectation,J,Loss
alg,,,,,,,,,,
OPT,2.0,0.5,0.2,5.22±0.6,1.0±0.0,0.71±0.2,0.72±0.01,0.52±0.03,1.71±0.14,0.66±0.06
ROAR,2.0,0.5,0.2,3.51±0.96,0.84±0.15,0.04±0.04,0.61±0.05,0.32±0.07,2.24±0.41,1.54±0.55